FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --default-timeout=120 --no-cache-dir -r requirements.txt
RUN python -c 'from sentence_transformers import SentenceTransformer'

COPY app/ ./app/
COPY data/databases/ ./data/databases/
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
